/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rainbowsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ModelsExposedMetadata type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModelsExposedMetadata{}

// ModelsExposedMetadata struct for ModelsExposedMetadata
type ModelsExposedMetadata struct {
	AnimationUrl *string `json:"animation_url,omitempty"`
	AppId *int32 `json:"app_id,omitempty"`
	Attributes []ModelsExposedMetadataAttribute `json:"attributes,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	DeletedAt *GormDeletedAt `json:"deleted_at,omitempty"`
	Description string `json:"description"`
	ExternalLink *string `json:"external_link,omitempty"`
	Id *int32 `json:"id,omitempty"`
	Image string `json:"image"`
	MetadataId *string `json:"metadata_id,omitempty"`
	Name string `json:"name"`
	UpdatedAt *string `json:"updated_at,omitempty"`
	Uri *string `json:"uri,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelsExposedMetadata ModelsExposedMetadata

// NewModelsExposedMetadata instantiates a new ModelsExposedMetadata object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsExposedMetadata(description string, image string, name string) *ModelsExposedMetadata {
	this := ModelsExposedMetadata{}
	this.Description = description
	this.Image = image
	this.Name = name
	return &this
}

// NewModelsExposedMetadataWithDefaults instantiates a new ModelsExposedMetadata object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsExposedMetadataWithDefaults() *ModelsExposedMetadata {
	this := ModelsExposedMetadata{}
	return &this
}

// GetAnimationUrl returns the AnimationUrl field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetAnimationUrl() string {
	if o == nil || IsNil(o.AnimationUrl) {
		var ret string
		return ret
	}
	return *o.AnimationUrl
}

// GetAnimationUrlOk returns a tuple with the AnimationUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetAnimationUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AnimationUrl) {
		return nil, false
	}
	return o.AnimationUrl, true
}

// HasAnimationUrl returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasAnimationUrl() bool {
	if o != nil && !IsNil(o.AnimationUrl) {
		return true
	}

	return false
}

// SetAnimationUrl gets a reference to the given string and assigns it to the AnimationUrl field.
func (o *ModelsExposedMetadata) SetAnimationUrl(v string) {
	o.AnimationUrl = &v
}

// GetAppId returns the AppId field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetAppId() int32 {
	if o == nil || IsNil(o.AppId) {
		var ret int32
		return ret
	}
	return *o.AppId
}

// GetAppIdOk returns a tuple with the AppId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetAppIdOk() (*int32, bool) {
	if o == nil || IsNil(o.AppId) {
		return nil, false
	}
	return o.AppId, true
}

// HasAppId returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasAppId() bool {
	if o != nil && !IsNil(o.AppId) {
		return true
	}

	return false
}

// SetAppId gets a reference to the given int32 and assigns it to the AppId field.
func (o *ModelsExposedMetadata) SetAppId(v int32) {
	o.AppId = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetAttributes() []ModelsExposedMetadataAttribute {
	if o == nil || IsNil(o.Attributes) {
		var ret []ModelsExposedMetadataAttribute
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetAttributesOk() ([]ModelsExposedMetadataAttribute, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []ModelsExposedMetadataAttribute and assigns it to the Attributes field.
func (o *ModelsExposedMetadata) SetAttributes(v []ModelsExposedMetadataAttribute) {
	o.Attributes = v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *ModelsExposedMetadata) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetDeletedAt returns the DeletedAt field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetDeletedAt() GormDeletedAt {
	if o == nil || IsNil(o.DeletedAt) {
		var ret GormDeletedAt
		return ret
	}
	return *o.DeletedAt
}

// GetDeletedAtOk returns a tuple with the DeletedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetDeletedAtOk() (*GormDeletedAt, bool) {
	if o == nil || IsNil(o.DeletedAt) {
		return nil, false
	}
	return o.DeletedAt, true
}

// HasDeletedAt returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasDeletedAt() bool {
	if o != nil && !IsNil(o.DeletedAt) {
		return true
	}

	return false
}

// SetDeletedAt gets a reference to the given GormDeletedAt and assigns it to the DeletedAt field.
func (o *ModelsExposedMetadata) SetDeletedAt(v GormDeletedAt) {
	o.DeletedAt = &v
}

// GetDescription returns the Description field value
func (o *ModelsExposedMetadata) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *ModelsExposedMetadata) SetDescription(v string) {
	o.Description = v
}

// GetExternalLink returns the ExternalLink field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetExternalLink() string {
	if o == nil || IsNil(o.ExternalLink) {
		var ret string
		return ret
	}
	return *o.ExternalLink
}

// GetExternalLinkOk returns a tuple with the ExternalLink field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetExternalLinkOk() (*string, bool) {
	if o == nil || IsNil(o.ExternalLink) {
		return nil, false
	}
	return o.ExternalLink, true
}

// HasExternalLink returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasExternalLink() bool {
	if o != nil && !IsNil(o.ExternalLink) {
		return true
	}

	return false
}

// SetExternalLink gets a reference to the given string and assigns it to the ExternalLink field.
func (o *ModelsExposedMetadata) SetExternalLink(v string) {
	o.ExternalLink = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ModelsExposedMetadata) SetId(v int32) {
	o.Id = &v
}

// GetImage returns the Image field value
func (o *ModelsExposedMetadata) GetImage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetImageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *ModelsExposedMetadata) SetImage(v string) {
	o.Image = v
}

// GetMetadataId returns the MetadataId field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetMetadataId() string {
	if o == nil || IsNil(o.MetadataId) {
		var ret string
		return ret
	}
	return *o.MetadataId
}

// GetMetadataIdOk returns a tuple with the MetadataId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetMetadataIdOk() (*string, bool) {
	if o == nil || IsNil(o.MetadataId) {
		return nil, false
	}
	return o.MetadataId, true
}

// HasMetadataId returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasMetadataId() bool {
	if o != nil && !IsNil(o.MetadataId) {
		return true
	}

	return false
}

// SetMetadataId gets a reference to the given string and assigns it to the MetadataId field.
func (o *ModelsExposedMetadata) SetMetadataId(v string) {
	o.MetadataId = &v
}

// GetName returns the Name field value
func (o *ModelsExposedMetadata) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ModelsExposedMetadata) SetName(v string) {
	o.Name = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetUpdatedAt() string {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret string
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetUpdatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given string and assigns it to the UpdatedAt field.
func (o *ModelsExposedMetadata) SetUpdatedAt(v string) {
	o.UpdatedAt = &v
}

// GetUri returns the Uri field value if set, zero value otherwise.
func (o *ModelsExposedMetadata) GetUri() string {
	if o == nil || IsNil(o.Uri) {
		var ret string
		return ret
	}
	return *o.Uri
}

// GetUriOk returns a tuple with the Uri field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsExposedMetadata) GetUriOk() (*string, bool) {
	if o == nil || IsNil(o.Uri) {
		return nil, false
	}
	return o.Uri, true
}

// HasUri returns a boolean if a field has been set.
func (o *ModelsExposedMetadata) HasUri() bool {
	if o != nil && !IsNil(o.Uri) {
		return true
	}

	return false
}

// SetUri gets a reference to the given string and assigns it to the Uri field.
func (o *ModelsExposedMetadata) SetUri(v string) {
	o.Uri = &v
}

func (o ModelsExposedMetadata) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModelsExposedMetadata) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AnimationUrl) {
		toSerialize["animation_url"] = o.AnimationUrl
	}
	if !IsNil(o.AppId) {
		toSerialize["app_id"] = o.AppId
	}
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.DeletedAt) {
		toSerialize["deleted_at"] = o.DeletedAt
	}
	toSerialize["description"] = o.Description
	if !IsNil(o.ExternalLink) {
		toSerialize["external_link"] = o.ExternalLink
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["image"] = o.Image
	if !IsNil(o.MetadataId) {
		toSerialize["metadata_id"] = o.MetadataId
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Uri) {
		toSerialize["uri"] = o.Uri
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModelsExposedMetadata) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"description",
		"image",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModelsExposedMetadata := _ModelsExposedMetadata{}

	err = json.Unmarshal(data, &varModelsExposedMetadata)

	if err != nil {
		return err
	}

	*o = ModelsExposedMetadata(varModelsExposedMetadata)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "animation_url")
		delete(additionalProperties, "app_id")
		delete(additionalProperties, "attributes")
		delete(additionalProperties, "created_at")
		delete(additionalProperties, "deleted_at")
		delete(additionalProperties, "description")
		delete(additionalProperties, "external_link")
		delete(additionalProperties, "id")
		delete(additionalProperties, "image")
		delete(additionalProperties, "metadata_id")
		delete(additionalProperties, "name")
		delete(additionalProperties, "updated_at")
		delete(additionalProperties, "uri")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelsExposedMetadata struct {
	value *ModelsExposedMetadata
	isSet bool
}

func (v NullableModelsExposedMetadata) Get() *ModelsExposedMetadata {
	return v.value
}

func (v *NullableModelsExposedMetadata) Set(val *ModelsExposedMetadata) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsExposedMetadata) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsExposedMetadata) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsExposedMetadata(val *ModelsExposedMetadata) *NullableModelsExposedMetadata {
	return &NullableModelsExposedMetadata{value: val, isSet: true}
}

func (v NullableModelsExposedMetadata) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsExposedMetadata) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


