/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rainbowsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ServicesTransferItemDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesTransferItemDto{}

// ServicesTransferItemDto struct for ServicesTransferItemDto
type ServicesTransferItemDto struct {
	Amount *int32 `json:"amount,omitempty"`
	TokenId string `json:"token_id"`
	TransferFromAddress string `json:"transfer_from_address"`
	TransferToAddress string `json:"transfer_to_address"`
	AdditionalProperties map[string]interface{}
}

type _ServicesTransferItemDto ServicesTransferItemDto

// NewServicesTransferItemDto instantiates a new ServicesTransferItemDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesTransferItemDto(tokenId string, transferFromAddress string, transferToAddress string) *ServicesTransferItemDto {
	this := ServicesTransferItemDto{}
	this.TokenId = tokenId
	this.TransferFromAddress = transferFromAddress
	this.TransferToAddress = transferToAddress
	return &this
}

// NewServicesTransferItemDtoWithDefaults instantiates a new ServicesTransferItemDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesTransferItemDtoWithDefaults() *ServicesTransferItemDto {
	this := ServicesTransferItemDto{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ServicesTransferItemDto) GetAmount() int32 {
	if o == nil || IsNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesTransferItemDto) GetAmountOk() (*int32, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ServicesTransferItemDto) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ServicesTransferItemDto) SetAmount(v int32) {
	o.Amount = &v
}

// GetTokenId returns the TokenId field value
func (o *ServicesTransferItemDto) GetTokenId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TokenId
}

// GetTokenIdOk returns a tuple with the TokenId field value
// and a boolean to check if the value has been set.
func (o *ServicesTransferItemDto) GetTokenIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TokenId, true
}

// SetTokenId sets field value
func (o *ServicesTransferItemDto) SetTokenId(v string) {
	o.TokenId = v
}

// GetTransferFromAddress returns the TransferFromAddress field value
func (o *ServicesTransferItemDto) GetTransferFromAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransferFromAddress
}

// GetTransferFromAddressOk returns a tuple with the TransferFromAddress field value
// and a boolean to check if the value has been set.
func (o *ServicesTransferItemDto) GetTransferFromAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransferFromAddress, true
}

// SetTransferFromAddress sets field value
func (o *ServicesTransferItemDto) SetTransferFromAddress(v string) {
	o.TransferFromAddress = v
}

// GetTransferToAddress returns the TransferToAddress field value
func (o *ServicesTransferItemDto) GetTransferToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TransferToAddress
}

// GetTransferToAddressOk returns a tuple with the TransferToAddress field value
// and a boolean to check if the value has been set.
func (o *ServicesTransferItemDto) GetTransferToAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TransferToAddress, true
}

// SetTransferToAddress sets field value
func (o *ServicesTransferItemDto) SetTransferToAddress(v string) {
	o.TransferToAddress = v
}

func (o ServicesTransferItemDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesTransferItemDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	toSerialize["token_id"] = o.TokenId
	toSerialize["transfer_from_address"] = o.TransferFromAddress
	toSerialize["transfer_to_address"] = o.TransferToAddress

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServicesTransferItemDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"token_id",
		"transfer_from_address",
		"transfer_to_address",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServicesTransferItemDto := _ServicesTransferItemDto{}

	err = json.Unmarshal(data, &varServicesTransferItemDto)

	if err != nil {
		return err
	}

	*o = ServicesTransferItemDto(varServicesTransferItemDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "token_id")
		delete(additionalProperties, "transfer_from_address")
		delete(additionalProperties, "transfer_to_address")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServicesTransferItemDto struct {
	value *ServicesTransferItemDto
	isSet bool
}

func (v NullableServicesTransferItemDto) Get() *ServicesTransferItemDto {
	return v.value
}

func (v *NullableServicesTransferItemDto) Set(val *ServicesTransferItemDto) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesTransferItemDto) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesTransferItemDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesTransferItemDto(val *ServicesTransferItemDto) *NullableServicesTransferItemDto {
	return &NullableServicesTransferItemDto{value: val, isSet: true}
}

func (v NullableServicesTransferItemDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesTransferItemDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


