/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rainbowsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ServicesAppBatchMintByMetaUriDto type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesAppBatchMintByMetaUriDto{}

// ServicesAppBatchMintByMetaUriDto struct for ServicesAppBatchMintByMetaUriDto
type ServicesAppBatchMintByMetaUriDto struct {
	Chain string `json:"chain"`
	ContractAddress string `json:"contract_address"`
	MintItems []ServicesMintItemDto `json:"mint_items"`
	AdditionalProperties map[string]interface{}
}

type _ServicesAppBatchMintByMetaUriDto ServicesAppBatchMintByMetaUriDto

// NewServicesAppBatchMintByMetaUriDto instantiates a new ServicesAppBatchMintByMetaUriDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesAppBatchMintByMetaUriDto(chain string, contractAddress string, mintItems []ServicesMintItemDto) *ServicesAppBatchMintByMetaUriDto {
	this := ServicesAppBatchMintByMetaUriDto{}
	this.Chain = chain
	this.ContractAddress = contractAddress
	this.MintItems = mintItems
	return &this
}

// NewServicesAppBatchMintByMetaUriDtoWithDefaults instantiates a new ServicesAppBatchMintByMetaUriDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesAppBatchMintByMetaUriDtoWithDefaults() *ServicesAppBatchMintByMetaUriDto {
	this := ServicesAppBatchMintByMetaUriDto{}
	return &this
}

// GetChain returns the Chain field value
func (o *ServicesAppBatchMintByMetaUriDto) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintByMetaUriDto) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *ServicesAppBatchMintByMetaUriDto) SetChain(v string) {
	o.Chain = v
}

// GetContractAddress returns the ContractAddress field value
func (o *ServicesAppBatchMintByMetaUriDto) GetContractAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintByMetaUriDto) GetContractAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractAddress, true
}

// SetContractAddress sets field value
func (o *ServicesAppBatchMintByMetaUriDto) SetContractAddress(v string) {
	o.ContractAddress = v
}

// GetMintItems returns the MintItems field value
func (o *ServicesAppBatchMintByMetaUriDto) GetMintItems() []ServicesMintItemDto {
	if o == nil {
		var ret []ServicesMintItemDto
		return ret
	}

	return o.MintItems
}

// GetMintItemsOk returns a tuple with the MintItems field value
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintByMetaUriDto) GetMintItemsOk() ([]ServicesMintItemDto, bool) {
	if o == nil {
		return nil, false
	}
	return o.MintItems, true
}

// SetMintItems sets field value
func (o *ServicesAppBatchMintByMetaUriDto) SetMintItems(v []ServicesMintItemDto) {
	o.MintItems = v
}

func (o ServicesAppBatchMintByMetaUriDto) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesAppBatchMintByMetaUriDto) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["chain"] = o.Chain
	toSerialize["contract_address"] = o.ContractAddress
	toSerialize["mint_items"] = o.MintItems

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServicesAppBatchMintByMetaUriDto) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"chain",
		"contract_address",
		"mint_items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServicesAppBatchMintByMetaUriDto := _ServicesAppBatchMintByMetaUriDto{}

	err = json.Unmarshal(data, &varServicesAppBatchMintByMetaUriDto)

	if err != nil {
		return err
	}

	*o = ServicesAppBatchMintByMetaUriDto(varServicesAppBatchMintByMetaUriDto)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "chain")
		delete(additionalProperties, "contract_address")
		delete(additionalProperties, "mint_items")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServicesAppBatchMintByMetaUriDto struct {
	value *ServicesAppBatchMintByMetaUriDto
	isSet bool
}

func (v NullableServicesAppBatchMintByMetaUriDto) Get() *ServicesAppBatchMintByMetaUriDto {
	return v.value
}

func (v *NullableServicesAppBatchMintByMetaUriDto) Set(val *ServicesAppBatchMintByMetaUriDto) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesAppBatchMintByMetaUriDto) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesAppBatchMintByMetaUriDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesAppBatchMintByMetaUriDto(val *ServicesAppBatchMintByMetaUriDto) *NullableServicesAppBatchMintByMetaUriDto {
	return &NullableServicesAppBatchMintByMetaUriDto{value: val, isSet: true}
}

func (v NullableServicesAppBatchMintByMetaUriDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesAppBatchMintByMetaUriDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


