/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rainbowsdk

import (
	"encoding/json"
	"fmt"
)

// checks if the ServicesBuildNftSetApprovalForAllTxReq type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesBuildNftSetApprovalForAllTxReq{}

// ServicesBuildNftSetApprovalForAllTxReq struct for ServicesBuildNftSetApprovalForAllTxReq
type ServicesBuildNftSetApprovalForAllTxReq struct {
	Approved bool `json:"approved"`
	Chain string `json:"chain"`
	ContractAddress string `json:"contract_address"`
	ContractType string `json:"contract_type"`
	From string `json:"from"`
	Operator string `json:"operator"`
	AdditionalProperties map[string]interface{}
}

type _ServicesBuildNftSetApprovalForAllTxReq ServicesBuildNftSetApprovalForAllTxReq

// NewServicesBuildNftSetApprovalForAllTxReq instantiates a new ServicesBuildNftSetApprovalForAllTxReq object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesBuildNftSetApprovalForAllTxReq(approved bool, chain string, contractAddress string, contractType string, from string, operator string) *ServicesBuildNftSetApprovalForAllTxReq {
	this := ServicesBuildNftSetApprovalForAllTxReq{}
	this.Approved = approved
	this.Chain = chain
	this.ContractAddress = contractAddress
	this.ContractType = contractType
	this.From = from
	this.Operator = operator
	return &this
}

// NewServicesBuildNftSetApprovalForAllTxReqWithDefaults instantiates a new ServicesBuildNftSetApprovalForAllTxReq object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesBuildNftSetApprovalForAllTxReqWithDefaults() *ServicesBuildNftSetApprovalForAllTxReq {
	this := ServicesBuildNftSetApprovalForAllTxReq{}
	return &this
}

// GetApproved returns the Approved field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetApproved() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Approved
}

// GetApprovedOk returns a tuple with the Approved field value
// and a boolean to check if the value has been set.
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetApprovedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Approved, true
}

// SetApproved sets field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) SetApproved(v bool) {
	o.Approved = v
}

// GetChain returns the Chain field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetChainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) SetChain(v string) {
	o.Chain = v
}

// GetContractAddress returns the ContractAddress field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetContractAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value
// and a boolean to check if the value has been set.
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetContractAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractAddress, true
}

// SetContractAddress sets field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) SetContractAddress(v string) {
	o.ContractAddress = v
}

// GetContractType returns the ContractType field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetContractType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContractType
}

// GetContractTypeOk returns a tuple with the ContractType field value
// and a boolean to check if the value has been set.
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetContractTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContractType, true
}

// SetContractType sets field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) SetContractType(v string) {
	o.ContractType = v
}

// GetFrom returns the From field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) SetFrom(v string) {
	o.From = v
}

// GetOperator returns the Operator field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetOperator() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Operator
}

// GetOperatorOk returns a tuple with the Operator field value
// and a boolean to check if the value has been set.
func (o *ServicesBuildNftSetApprovalForAllTxReq) GetOperatorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Operator, true
}

// SetOperator sets field value
func (o *ServicesBuildNftSetApprovalForAllTxReq) SetOperator(v string) {
	o.Operator = v
}

func (o ServicesBuildNftSetApprovalForAllTxReq) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesBuildNftSetApprovalForAllTxReq) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["approved"] = o.Approved
	toSerialize["chain"] = o.Chain
	toSerialize["contract_address"] = o.ContractAddress
	toSerialize["contract_type"] = o.ContractType
	toSerialize["from"] = o.From
	toSerialize["operator"] = o.Operator

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServicesBuildNftSetApprovalForAllTxReq) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"approved",
		"chain",
		"contract_address",
		"contract_type",
		"from",
		"operator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varServicesBuildNftSetApprovalForAllTxReq := _ServicesBuildNftSetApprovalForAllTxReq{}

	err = json.Unmarshal(data, &varServicesBuildNftSetApprovalForAllTxReq)

	if err != nil {
		return err
	}

	*o = ServicesBuildNftSetApprovalForAllTxReq(varServicesBuildNftSetApprovalForAllTxReq)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "approved")
		delete(additionalProperties, "chain")
		delete(additionalProperties, "contract_address")
		delete(additionalProperties, "contract_type")
		delete(additionalProperties, "from")
		delete(additionalProperties, "operator")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServicesBuildNftSetApprovalForAllTxReq struct {
	value *ServicesBuildNftSetApprovalForAllTxReq
	isSet bool
}

func (v NullableServicesBuildNftSetApprovalForAllTxReq) Get() *ServicesBuildNftSetApprovalForAllTxReq {
	return v.value
}

func (v *NullableServicesBuildNftSetApprovalForAllTxReq) Set(val *ServicesBuildNftSetApprovalForAllTxReq) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesBuildNftSetApprovalForAllTxReq) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesBuildNftSetApprovalForAllTxReq) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesBuildNftSetApprovalForAllTxReq(val *ServicesBuildNftSetApprovalForAllTxReq) *NullableServicesBuildNftSetApprovalForAllTxReq {
	return &NullableServicesBuildNftSetApprovalForAllTxReq{value: val, isSet: true}
}

func (v NullableServicesBuildNftSetApprovalForAllTxReq) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesBuildNftSetApprovalForAllTxReq) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


