/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rainbowsdk

import (
	"encoding/json"
)

// ModelsContractRuntimeProfile struct for ModelsContractRuntimeProfile
type ModelsContractRuntimeProfile struct {
	Contract *ModelsContract `json:"contract,omitempty"`
	MaxTokenId *int32 `json:"max_token_id,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModelsContractRuntimeProfile ModelsContractRuntimeProfile

// NewModelsContractRuntimeProfile instantiates a new ModelsContractRuntimeProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModelsContractRuntimeProfile() *ModelsContractRuntimeProfile {
	this := ModelsContractRuntimeProfile{}
	return &this
}

// NewModelsContractRuntimeProfileWithDefaults instantiates a new ModelsContractRuntimeProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModelsContractRuntimeProfileWithDefaults() *ModelsContractRuntimeProfile {
	this := ModelsContractRuntimeProfile{}
	return &this
}

// GetContract returns the Contract field value if set, zero value otherwise.
func (o *ModelsContractRuntimeProfile) GetContract() ModelsContract {
	if o == nil || isNil(o.Contract) {
		var ret ModelsContract
		return ret
	}
	return *o.Contract
}

// GetContractOk returns a tuple with the Contract field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsContractRuntimeProfile) GetContractOk() (*ModelsContract, bool) {
	if o == nil || isNil(o.Contract) {
    return nil, false
	}
	return o.Contract, true
}

// HasContract returns a boolean if a field has been set.
func (o *ModelsContractRuntimeProfile) HasContract() bool {
	if o != nil && !isNil(o.Contract) {
		return true
	}

	return false
}

// SetContract gets a reference to the given ModelsContract and assigns it to the Contract field.
func (o *ModelsContractRuntimeProfile) SetContract(v ModelsContract) {
	o.Contract = &v
}

// GetMaxTokenId returns the MaxTokenId field value if set, zero value otherwise.
func (o *ModelsContractRuntimeProfile) GetMaxTokenId() int32 {
	if o == nil || isNil(o.MaxTokenId) {
		var ret int32
		return ret
	}
	return *o.MaxTokenId
}

// GetMaxTokenIdOk returns a tuple with the MaxTokenId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModelsContractRuntimeProfile) GetMaxTokenIdOk() (*int32, bool) {
	if o == nil || isNil(o.MaxTokenId) {
    return nil, false
	}
	return o.MaxTokenId, true
}

// HasMaxTokenId returns a boolean if a field has been set.
func (o *ModelsContractRuntimeProfile) HasMaxTokenId() bool {
	if o != nil && !isNil(o.MaxTokenId) {
		return true
	}

	return false
}

// SetMaxTokenId gets a reference to the given int32 and assigns it to the MaxTokenId field.
func (o *ModelsContractRuntimeProfile) SetMaxTokenId(v int32) {
	o.MaxTokenId = &v
}

func (o ModelsContractRuntimeProfile) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Contract) {
		toSerialize["contract"] = o.Contract
	}
	if !isNil(o.MaxTokenId) {
		toSerialize["max_token_id"] = o.MaxTokenId
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ModelsContractRuntimeProfile) UnmarshalJSON(bytes []byte) (err error) {
	varModelsContractRuntimeProfile := _ModelsContractRuntimeProfile{}

	if err = json.Unmarshal(bytes, &varModelsContractRuntimeProfile); err == nil {
		*o = ModelsContractRuntimeProfile(varModelsContractRuntimeProfile)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "contract")
		delete(additionalProperties, "max_token_id")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModelsContractRuntimeProfile struct {
	value *ModelsContractRuntimeProfile
	isSet bool
}

func (v NullableModelsContractRuntimeProfile) Get() *ModelsContractRuntimeProfile {
	return v.value
}

func (v *NullableModelsContractRuntimeProfile) Set(val *ModelsContractRuntimeProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableModelsContractRuntimeProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableModelsContractRuntimeProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModelsContractRuntimeProfile(val *ModelsContractRuntimeProfile) *NullableModelsContractRuntimeProfile {
	return &NullableModelsContractRuntimeProfile{value: val, isSet: true}
}

func (v NullableModelsContractRuntimeProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModelsContractRuntimeProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


