/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rainbowsdk

import (
	"encoding/json"
)

// ServicesAppBatchMintMetaItemDto struct for ServicesAppBatchMintMetaItemDto
type ServicesAppBatchMintMetaItemDto struct {
	// amount on same token id, only erc1155 contract could set large than 1, others set null or 1
	Amount *int32 `json:"amount,omitempty"`
	AnimationUrl *string `json:"animation_url,omitempty"`
	Attributes []ModelsExposedMetadataAttribute `json:"attributes,omitempty"`
	Chain string `json:"chain"`
	ContractAddress *string `json:"contract_address,omitempty"`
	Description *string `json:"description,omitempty"`
	FileUrl string `json:"file_url"`
	MintToAddress string `json:"mint_to_address"`
	Name string `json:"name"`
	// mint number, everyone with different token id (not conflict with AmountOnSameTokenID)
	Number *int32 `json:"number,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServicesAppBatchMintMetaItemDto ServicesAppBatchMintMetaItemDto

// NewServicesAppBatchMintMetaItemDto instantiates a new ServicesAppBatchMintMetaItemDto object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesAppBatchMintMetaItemDto(chain string, fileUrl string, mintToAddress string, name string) *ServicesAppBatchMintMetaItemDto {
	this := ServicesAppBatchMintMetaItemDto{}
	this.Chain = chain
	this.FileUrl = fileUrl
	this.MintToAddress = mintToAddress
	this.Name = name
	return &this
}

// NewServicesAppBatchMintMetaItemDtoWithDefaults instantiates a new ServicesAppBatchMintMetaItemDto object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesAppBatchMintMetaItemDtoWithDefaults() *ServicesAppBatchMintMetaItemDto {
	this := ServicesAppBatchMintMetaItemDto{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ServicesAppBatchMintMetaItemDto) GetAmount() int32 {
	if o == nil || isNil(o.Amount) {
		var ret int32
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetAmountOk() (*int32, bool) {
	if o == nil || isNil(o.Amount) {
    return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ServicesAppBatchMintMetaItemDto) HasAmount() bool {
	if o != nil && !isNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given int32 and assigns it to the Amount field.
func (o *ServicesAppBatchMintMetaItemDto) SetAmount(v int32) {
	o.Amount = &v
}

// GetAnimationUrl returns the AnimationUrl field value if set, zero value otherwise.
func (o *ServicesAppBatchMintMetaItemDto) GetAnimationUrl() string {
	if o == nil || isNil(o.AnimationUrl) {
		var ret string
		return ret
	}
	return *o.AnimationUrl
}

// GetAnimationUrlOk returns a tuple with the AnimationUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetAnimationUrlOk() (*string, bool) {
	if o == nil || isNil(o.AnimationUrl) {
    return nil, false
	}
	return o.AnimationUrl, true
}

// HasAnimationUrl returns a boolean if a field has been set.
func (o *ServicesAppBatchMintMetaItemDto) HasAnimationUrl() bool {
	if o != nil && !isNil(o.AnimationUrl) {
		return true
	}

	return false
}

// SetAnimationUrl gets a reference to the given string and assigns it to the AnimationUrl field.
func (o *ServicesAppBatchMintMetaItemDto) SetAnimationUrl(v string) {
	o.AnimationUrl = &v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *ServicesAppBatchMintMetaItemDto) GetAttributes() []ModelsExposedMetadataAttribute {
	if o == nil || isNil(o.Attributes) {
		var ret []ModelsExposedMetadataAttribute
		return ret
	}
	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetAttributesOk() ([]ModelsExposedMetadataAttribute, bool) {
	if o == nil || isNil(o.Attributes) {
    return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *ServicesAppBatchMintMetaItemDto) HasAttributes() bool {
	if o != nil && !isNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given []ModelsExposedMetadataAttribute and assigns it to the Attributes field.
func (o *ServicesAppBatchMintMetaItemDto) SetAttributes(v []ModelsExposedMetadataAttribute) {
	o.Attributes = v
}

// GetChain returns the Chain field value
func (o *ServicesAppBatchMintMetaItemDto) GetChain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Chain
}

// GetChainOk returns a tuple with the Chain field value
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetChainOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Chain, true
}

// SetChain sets field value
func (o *ServicesAppBatchMintMetaItemDto) SetChain(v string) {
	o.Chain = v
}

// GetContractAddress returns the ContractAddress field value if set, zero value otherwise.
func (o *ServicesAppBatchMintMetaItemDto) GetContractAddress() string {
	if o == nil || isNil(o.ContractAddress) {
		var ret string
		return ret
	}
	return *o.ContractAddress
}

// GetContractAddressOk returns a tuple with the ContractAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetContractAddressOk() (*string, bool) {
	if o == nil || isNil(o.ContractAddress) {
    return nil, false
	}
	return o.ContractAddress, true
}

// HasContractAddress returns a boolean if a field has been set.
func (o *ServicesAppBatchMintMetaItemDto) HasContractAddress() bool {
	if o != nil && !isNil(o.ContractAddress) {
		return true
	}

	return false
}

// SetContractAddress gets a reference to the given string and assigns it to the ContractAddress field.
func (o *ServicesAppBatchMintMetaItemDto) SetContractAddress(v string) {
	o.ContractAddress = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ServicesAppBatchMintMetaItemDto) GetDescription() string {
	if o == nil || isNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetDescriptionOk() (*string, bool) {
	if o == nil || isNil(o.Description) {
    return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ServicesAppBatchMintMetaItemDto) HasDescription() bool {
	if o != nil && !isNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ServicesAppBatchMintMetaItemDto) SetDescription(v string) {
	o.Description = &v
}

// GetFileUrl returns the FileUrl field value
func (o *ServicesAppBatchMintMetaItemDto) GetFileUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FileUrl
}

// GetFileUrlOk returns a tuple with the FileUrl field value
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetFileUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.FileUrl, true
}

// SetFileUrl sets field value
func (o *ServicesAppBatchMintMetaItemDto) SetFileUrl(v string) {
	o.FileUrl = v
}

// GetMintToAddress returns the MintToAddress field value
func (o *ServicesAppBatchMintMetaItemDto) GetMintToAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MintToAddress
}

// GetMintToAddressOk returns a tuple with the MintToAddress field value
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetMintToAddressOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.MintToAddress, true
}

// SetMintToAddress sets field value
func (o *ServicesAppBatchMintMetaItemDto) SetMintToAddress(v string) {
	o.MintToAddress = v
}

// GetName returns the Name field value
func (o *ServicesAppBatchMintMetaItemDto) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetNameOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ServicesAppBatchMintMetaItemDto) SetName(v string) {
	o.Name = v
}

// GetNumber returns the Number field value if set, zero value otherwise.
func (o *ServicesAppBatchMintMetaItemDto) GetNumber() int32 {
	if o == nil || isNil(o.Number) {
		var ret int32
		return ret
	}
	return *o.Number
}

// GetNumberOk returns a tuple with the Number field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesAppBatchMintMetaItemDto) GetNumberOk() (*int32, bool) {
	if o == nil || isNil(o.Number) {
    return nil, false
	}
	return o.Number, true
}

// HasNumber returns a boolean if a field has been set.
func (o *ServicesAppBatchMintMetaItemDto) HasNumber() bool {
	if o != nil && !isNil(o.Number) {
		return true
	}

	return false
}

// SetNumber gets a reference to the given int32 and assigns it to the Number field.
func (o *ServicesAppBatchMintMetaItemDto) SetNumber(v int32) {
	o.Number = &v
}

func (o ServicesAppBatchMintMetaItemDto) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if !isNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !isNil(o.AnimationUrl) {
		toSerialize["animation_url"] = o.AnimationUrl
	}
	if !isNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if true {
		toSerialize["chain"] = o.Chain
	}
	if !isNil(o.ContractAddress) {
		toSerialize["contract_address"] = o.ContractAddress
	}
	if !isNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["file_url"] = o.FileUrl
	}
	if true {
		toSerialize["mint_to_address"] = o.MintToAddress
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if !isNil(o.Number) {
		toSerialize["number"] = o.Number
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return json.Marshal(toSerialize)
}

func (o *ServicesAppBatchMintMetaItemDto) UnmarshalJSON(bytes []byte) (err error) {
	varServicesAppBatchMintMetaItemDto := _ServicesAppBatchMintMetaItemDto{}

	if err = json.Unmarshal(bytes, &varServicesAppBatchMintMetaItemDto); err == nil {
		*o = ServicesAppBatchMintMetaItemDto(varServicesAppBatchMintMetaItemDto)
	}

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(bytes, &additionalProperties); err == nil {
		delete(additionalProperties, "amount")
		delete(additionalProperties, "animation_url")
		delete(additionalProperties, "attributes")
		delete(additionalProperties, "chain")
		delete(additionalProperties, "contract_address")
		delete(additionalProperties, "description")
		delete(additionalProperties, "file_url")
		delete(additionalProperties, "mint_to_address")
		delete(additionalProperties, "name")
		delete(additionalProperties, "number")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServicesAppBatchMintMetaItemDto struct {
	value *ServicesAppBatchMintMetaItemDto
	isSet bool
}

func (v NullableServicesAppBatchMintMetaItemDto) Get() *ServicesAppBatchMintMetaItemDto {
	return v.value
}

func (v *NullableServicesAppBatchMintMetaItemDto) Set(val *ServicesAppBatchMintMetaItemDto) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesAppBatchMintMetaItemDto) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesAppBatchMintMetaItemDto) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesAppBatchMintMetaItemDto(val *ServicesAppBatchMintMetaItemDto) *NullableServicesAppBatchMintMetaItemDto {
	return &NullableServicesAppBatchMintMetaItemDto{value: val, isSet: true}
}

func (v NullableServicesAppBatchMintMetaItemDto) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesAppBatchMintMetaItemDto) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


