/*
Rainbow-API

The responses of the open api in swagger focus on the data field rather than the code and the message fields

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package rainbowsdk

import (
	"encoding/json"
)

// checks if the ServicesUploadFilesResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ServicesUploadFilesResponse{}

// ServicesUploadFilesResponse struct for ServicesUploadFilesResponse
type ServicesUploadFilesResponse struct {
	FileName *string `json:"file_name,omitempty"`
	FileSize *int32 `json:"file_size,omitempty"`
	FileType *string `json:"file_type,omitempty"`
	FileUrl *string `json:"file_url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ServicesUploadFilesResponse ServicesUploadFilesResponse

// NewServicesUploadFilesResponse instantiates a new ServicesUploadFilesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewServicesUploadFilesResponse() *ServicesUploadFilesResponse {
	this := ServicesUploadFilesResponse{}
	return &this
}

// NewServicesUploadFilesResponseWithDefaults instantiates a new ServicesUploadFilesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewServicesUploadFilesResponseWithDefaults() *ServicesUploadFilesResponse {
	this := ServicesUploadFilesResponse{}
	return &this
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *ServicesUploadFilesResponse) GetFileName() string {
	if o == nil || IsNil(o.FileName) {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesUploadFilesResponse) GetFileNameOk() (*string, bool) {
	if o == nil || IsNil(o.FileName) {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *ServicesUploadFilesResponse) HasFileName() bool {
	if o != nil && !IsNil(o.FileName) {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *ServicesUploadFilesResponse) SetFileName(v string) {
	o.FileName = &v
}

// GetFileSize returns the FileSize field value if set, zero value otherwise.
func (o *ServicesUploadFilesResponse) GetFileSize() int32 {
	if o == nil || IsNil(o.FileSize) {
		var ret int32
		return ret
	}
	return *o.FileSize
}

// GetFileSizeOk returns a tuple with the FileSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesUploadFilesResponse) GetFileSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.FileSize) {
		return nil, false
	}
	return o.FileSize, true
}

// HasFileSize returns a boolean if a field has been set.
func (o *ServicesUploadFilesResponse) HasFileSize() bool {
	if o != nil && !IsNil(o.FileSize) {
		return true
	}

	return false
}

// SetFileSize gets a reference to the given int32 and assigns it to the FileSize field.
func (o *ServicesUploadFilesResponse) SetFileSize(v int32) {
	o.FileSize = &v
}

// GetFileType returns the FileType field value if set, zero value otherwise.
func (o *ServicesUploadFilesResponse) GetFileType() string {
	if o == nil || IsNil(o.FileType) {
		var ret string
		return ret
	}
	return *o.FileType
}

// GetFileTypeOk returns a tuple with the FileType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesUploadFilesResponse) GetFileTypeOk() (*string, bool) {
	if o == nil || IsNil(o.FileType) {
		return nil, false
	}
	return o.FileType, true
}

// HasFileType returns a boolean if a field has been set.
func (o *ServicesUploadFilesResponse) HasFileType() bool {
	if o != nil && !IsNil(o.FileType) {
		return true
	}

	return false
}

// SetFileType gets a reference to the given string and assigns it to the FileType field.
func (o *ServicesUploadFilesResponse) SetFileType(v string) {
	o.FileType = &v
}

// GetFileUrl returns the FileUrl field value if set, zero value otherwise.
func (o *ServicesUploadFilesResponse) GetFileUrl() string {
	if o == nil || IsNil(o.FileUrl) {
		var ret string
		return ret
	}
	return *o.FileUrl
}

// GetFileUrlOk returns a tuple with the FileUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ServicesUploadFilesResponse) GetFileUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FileUrl) {
		return nil, false
	}
	return o.FileUrl, true
}

// HasFileUrl returns a boolean if a field has been set.
func (o *ServicesUploadFilesResponse) HasFileUrl() bool {
	if o != nil && !IsNil(o.FileUrl) {
		return true
	}

	return false
}

// SetFileUrl gets a reference to the given string and assigns it to the FileUrl field.
func (o *ServicesUploadFilesResponse) SetFileUrl(v string) {
	o.FileUrl = &v
}

func (o ServicesUploadFilesResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ServicesUploadFilesResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileName) {
		toSerialize["file_name"] = o.FileName
	}
	if !IsNil(o.FileSize) {
		toSerialize["file_size"] = o.FileSize
	}
	if !IsNil(o.FileType) {
		toSerialize["file_type"] = o.FileType
	}
	if !IsNil(o.FileUrl) {
		toSerialize["file_url"] = o.FileUrl
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ServicesUploadFilesResponse) UnmarshalJSON(data []byte) (err error) {
	varServicesUploadFilesResponse := _ServicesUploadFilesResponse{}

	err = json.Unmarshal(data, &varServicesUploadFilesResponse)

	if err != nil {
		return err
	}

	*o = ServicesUploadFilesResponse(varServicesUploadFilesResponse)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "file_name")
		delete(additionalProperties, "file_size")
		delete(additionalProperties, "file_type")
		delete(additionalProperties, "file_url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableServicesUploadFilesResponse struct {
	value *ServicesUploadFilesResponse
	isSet bool
}

func (v NullableServicesUploadFilesResponse) Get() *ServicesUploadFilesResponse {
	return v.value
}

func (v *NullableServicesUploadFilesResponse) Set(val *ServicesUploadFilesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableServicesUploadFilesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableServicesUploadFilesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableServicesUploadFilesResponse(val *ServicesUploadFilesResponse) *NullableServicesUploadFilesResponse {
	return &NullableServicesUploadFilesResponse{value: val, isSet: true}
}

func (v NullableServicesUploadFilesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableServicesUploadFilesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


